import test from 'node:test';import assert from 'node:assert/strict';
import {seed,applyCommand,total,ledger,cashSummary,roomAvailable,typeAvailable,currentRoom,today,plusDay,nights} from '../public/domain.js';
const day=today(),now=day+'T16:00';
function empty(){const s=seed();s.guests=[];s.bookings=[];s.transactions=[];s.activity=[];s.rooms.forEach(r=>r.status='ready');return s;}
function payload(extra={}){const start=day+'T15:00',end=plusDay(day,3)+'T11:00';return{status:'in-house',name:'Test Guest',idNumber:'TEST-ID',idType:'Passport',room:'101',type:'one',start,end,rates:nights(start,end).map((date,i)=>({date,amount:i===1?11000:10000})),paid:10000,deposit:5000,...extra};}
function create(db=empty(),extra={}){return applyCommand(db,'u1','create',payload(extra),now);}
test('variable nightly prices, separate deposit, exact balance',()=>{const {db,id}=create();assert.equal(total(db.bookings[0]),31000);assert.deepEqual(ledger(db,id),{paid:10000,deposit:5000,refunded:0});assert.equal(cashSummary(db,day).gross,15000);assert.equal(cashSummary(db,day).room,10000);});
test('occupied room conflict rejected, including unpaid guests',()=>{const {db}=create();assert.throws(()=>create(db),/already assigned/);});
test('late checkout cannot release room automatically',()=>{const {db}=create();db.bookings[0].end=day+'T11:00';assert.equal(roomAvailable(db,'101',now,plusDay(day,1)+'T11:00','',now),false);});
test('transfer preserves one stay, original collector/room, deposit and total',()=>{const {db,id}=create();const r=applyCommand(db,'u2','transfer',{id,room:'103',reason:'AC issue'},now);assert.equal(r.db.bookings.length,1);const b=r.db.bookings[0];assert.equal(currentRoom(b),'103');assert.equal(b.segments[0].end,now);assert.equal(b.segments[1].start,now);assert.equal(r.db.rooms[0].status,'dirty');assert.equal(r.db.transactions[0].room,'101');assert.equal(r.db.transactions[0].user,'u1');assert.equal(total(b),31000);assert.equal(ledger(r.db,id).deposit,5000);assert.equal(cashSummary(r.db,day).gross,15000);});
test('future reservations prevent overselling the last room type',()=>{const s=empty();s.rooms=s.rooms.slice(0,1);const {db}=create(s,{status:'reserved',room:'',idNumber:''});assert.equal(typeAvailable(db,'one',day+'T15:00',plusDay(day,2)+'T11:00'),false);assert.throws(()=>create(db,{status:'reserved',room:''}),/No rooms/);});
test('reservation conversion carries advance once',()=>{const {db,id}=create(empty(),{status:'reserved',room:'',idNumber:''});const r=applyCommand(db,'u2','check-in',{id,room:'102',idNumber:'TEST-2',idType:'Passport',paid:2000},now);assert.equal(r.db.bookings.length,1);assert.equal(r.db.bookings[0].assignedBy,'u2');assert.equal(ledger(r.db,id).paid,12000);assert.equal(cashSummary(r.db,day).gross,17000);assert.equal(cashSummary(r.db,day,day,'u1').room,10000);assert.equal(cashSummary(r.db,day,day,'u2').room,2000);});
test('extension preserves old rates and adds only new dates',()=>{const {db,id}=create();const b=db.bookings[0],end=plusDay(day,4)+'T11:00';const r=applyCommand(db,'u2','extend',{id,end,rates:[...b.rates,{date:plusDay(day,3),amount:12000}],paid:5000},now);assert.equal(total(r.db.bookings[0]),43000);assert.equal(ledger(r.db,id).paid,15000);assert.throws(()=>applyCommand(db,'u2','extend',{id,end,rates:[...b.rates.map(x=>({...x,amount:1})),{date:plusDay(day,3),amount:12000}]},now),/preserve/);});
test('refund is attributed to returning staff, not original collector',()=>{const {db,id}=create();const r=applyCommand(db,'u3','collect',{id,kind:'refund',amount:2000,note:'Agreed refund'},now);assert.equal(cashSummary(r.db,day,day,'u3').net,-2000);assert.equal(cashSummary(r.db,day).net,13000);});
test('deposit retention creates no fresh cash and no negative held balance',()=>{const {db,id}=create();const r=applyCommand(db,'u2','collect',{id,kind:'deposit-retained',amount:2000,note:'Damage'},now);assert.equal(ledger(r.db,id).deposit,3000);assert.equal(cashSummary(r.db,day).gross,15000);assert.throws(()=>applyCommand(r.db,'u2','collect',{id,kind:'deposit-return',amount:4000,note:'Return'},now),/exceeds/);});
test('checkout leaves guest history and requires balance/deposit acknowledgment',()=>{const {db,id}=create();assert.throws(()=>applyCommand(db,'u2','checkout',{id},now),/outstanding/);const r=applyCommand(db,'u2','checkout',{id,ackBalance:true,ackDeposit:true},now);assert.equal(r.db.bookings[0].status,'checked-out');assert.equal(r.db.bookings[0].actualOut,now);assert.equal(r.db.rooms[0].status,'dirty');assert.equal(r.db.guests.length,1);assert.equal(r.db.transactions.length,2);});
test('cancelled reservation releases inventory and preserves advance',()=>{const {db,id}=create(empty(),{status:'reserved',room:''});const r=applyCommand(db,'u2','cancel',{id,status:'cancelled',reason:'Plans changed'},now);assert.equal(ledger(r.db,id).paid,10000);assert.equal(r.db.bookings[0].status,'cancelled');assert.equal(cashSummary(r.db,day).room,10000);});
test('new day excludes previous receipts',()=>{const {db}=create();assert.equal(cashSummary(db,plusDay(day,1)).gross,0);});
test('identical names remain separate and returning guest can be selected',()=>{const {db,id}=create();const second=create(db,{room:'102'});assert.equal(second.db.guests.length,2);const third=create(second.db,{room:'103',guestId:db.bookings[0].guest});assert.equal(third.db.guests.length,2);assert.equal(third.db.bookings[2].guest,db.bookings[0].guest);});
test('reject malformed dates, fractional cents and inactive actor',()=>{assert.throws(()=>create(empty(),{end:'2026-02-31T11:00'}),/Checkout/);assert.throws(()=>create(empty(),{paid:1.5}),/valid/);const db=empty();db.staff[0].active=false;assert.throws(()=>create(db),/active staff/);});
test('same day stay charges explicit one-night rate',()=>{const p=payload({end:day+'T18:00',rates:[{date:day,amount:8000}]});const r=applyCommand(empty(),'u1','create',p,now);assert.equal(total(r.db.bookings[0]),8000);});
test('reservation edits preserve advance and validate changed type inventory',()=>{const {db,id}=create(empty(),{status:'reserved',room:''});const p={id,start:day+'T15:00',end:plusDay(day,2)+'T11:00',type:'two',room:'110',rates:[{date:day,amount:12000},{date:plusDay(day,1),amount:13000}],reason:'Changed travel dates'};const r=applyCommand(db,'u2','edit-reservation',p,now);assert.equal(total(r.db.bookings[0]),25000);assert.equal(ledger(r.db,id).paid,10000);assert.equal(r.db.bookings[0].room,'110');assert.match(r.db.activity.at(-1).detail,/Changed travel dates/);});
test('nightly repricing preserves cash and records old and new values',()=>{const {db,id}=create();const rates=db.bookings[0].rates.map(r=>({...r,amount:9000}));const r=applyCommand(db,'u2','rates',{id,rates,reason:'Agreed discount'},now);assert.equal(total(r.db.bookings[0]),27000);assert.equal(ledger(r.db,id).paid,10000);assert.match(r.db.activity.at(-1).detail,/11000/);assert.match(r.db.activity.at(-1).detail,/9000/);});
test('void excludes erroneous cash without pretending a physical refund',()=>{const {db,id}=create();const transaction=db.transactions.find(t=>t.kind==='payment').id;const r=applyCommand(db,'u2','void',{id,transaction,reason:'Duplicate typed receipt'},now);assert.equal(ledger(r.db,id).paid,0);assert.equal(cashSummary(r.db,day).gross,5000);assert.equal(cashSummary(r.db,day).returned,0);assert.equal(r.db.transactions[0].voidedBy,'u2');assert.equal(r.db.transactions.length,2);});
